title: Walter Shub
description: > # this means to ignore newlines until "baseurl:"
  I have experience with building Fullstack web and mobile applications
   using Javascript , Node, React, Redux , and React Native.
   I am thrilled by new challenges and by expanding my skills through
   learning new technologies or experimenting with new platforms.
   I choose my technologies based on the best way to complete the job and not what's in my comfort zone.
   I am constantly trying new things in my applications and bring a feeling of excitement and possibility to the teams I have worked on.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Walter Shub
tagline: Software Engineer
about-description: I have experience with building Fullstack web and mobile applications
 using Javascript , Node, React, Redux , and React Native.
 I am thrilled by new challenges and by expanding my skills through
 learning new technologies or experimenting with new platforms.
 I choose my technologies based on the best way to complete the job and not what's in my comfort zone.
 I am constantly trying new things in my applications and bring a feeling of excitement and possibility to the teams I have worked on.
pic: walt.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: waltershub@gmail.com # Add your Email address
phone: 848 299 9294 # Add your Phone number
website: waltershub.com # Add your website, do not add http://
linkedin: walter-shub-474823
github: waltershub # Add your Github handle
twitter: '@waltershub' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
